name: Build & Release
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: npm ci
      - name: publish to npm
        run: npm publish --access=publish
